name: run-action

on:
  push:
    branches:
      - 'dev'
      - 'main'
      - 'test-pr'
    pull_request:
      branches:
        - 'main'
        - 'dev'
    paths:
      - 'dist/**.js' # otherwise there's no real change in action
jobs:
  passing_scenarios:
    runs-on: ubuntu-latest
    name: Passing use case
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Action
        uses: ./ # this repo
        id: run_action
        with:
          path: 'fixtures/always-passing'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Outputs
        run: echo "${{ steps.run_action.outputs }}"


  failing_scenarios:
    runs-on: ubuntu-latest
    name: Failing use case
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Action
        uses: ./ # this repo
        id: run_action
        continue-on-error: true
        with:
          path: 'fixtures/'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Outputs
        run: echo "${{ steps.run_action.outputs }}"

      - name: Confirm Fixtures Failed
        run: |
          if [[ ${{ steps.run_action.outcome }} == 'failure' ]]; then exit 0; else exit 1; fi
