name: run-action

on:
  push:
    branches:
      - 'dev'
      - 'main'
    paths:
      - 'dist/**.js' # otherwise there's no real change in action
jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Test lowercsae-only GitHub Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # this repo
      - name: Run Action
        uses: ./
        id: run_action
        continue-on-error: true
        with:
          path: 'fixtures/'

      - name: Test Outputs
        run: |
          echo "${{ steps.run_action.outputs.time }}"
          echo "${{ steps.run_action.outputs.errors }}"
          echo "${{ steps.run_action.outputs.suggestion }}"

      - name: Confirm Fixtures Failed
        run: |
          if [[ ${{ steps.run_action.outcome }} == 'failure' ]]; then exit 0; else exit 1; fi
